Dz8
margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova pull request #12
Opened 2024-11-24 20:29 UTC by margo-yunanova

# Домашнее задание №

Что было сделано:
*
*
*

2024-11-25 04:26 UTC, sh4rkizz requested changes

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Стоит добавить такую же запись на страницу регистрации
А-ля `Already have an account? Sing in`

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Есть небольшая проблема с тем, что аватарка скукоживается, если последним сообщением является текст с переполнением [который транкируется элипсисом]

<img width="832" alt="изображение" src="https://github.com/user-attachments/assets/d0222380-86e9-4cb7-a521-b41c76be8a75">

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Появляется такая странная ошибка при обновлении

<img width="845" alt="изображение" src="https://github.com/user-attachments/assets/88943831-b2b8-46c5-934d-2c9d3059d56f">

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Непропорционально большая область для загрузки аватарки, предлагаю уменьшить ее

<img width="848" alt="изображение" src="https://github.com/user-attachments/assets/36485534-02a5-4839-a4b3-4950a67f27c5">

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Стоит разделить поле FullName на два поля: first_name + last_name, поскольку:
\- Так устроен бекенд
\- Разделять по пробелу некорректно, поскольку [даже в России] существует большое число людей с двойным именем-фамилией

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
По правильному - крестик должен появляться в той же области где рисовался бургер меню 
[он должен подменять его]

<img width="101" alt="изображение" src="https://github.com/user-attachments/assets/64c3a150-7c73-40bb-9457-e0169c85be54">

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Сейчас неясно как создать новый чат

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Также неясно как остановить запись ГС, поскольку весь интерфейс перекрывается фоном, а комбинации клавиш не работают

<img width="336" alt="изображение" src="https://github.com/user-attachments/assets/b65d5bf9-7d58-41e6-8324-73432a701353">

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
На странице реги присутствует ошибка фронта - где-то около парсинга токенов

<img width="586" alt="изображение" src="https://github.com/user-attachments/assets/3c7d6484-a2a8-42c8-b20a-ad08c1cd7cf5">

2024-11-25 04:26 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Крайне рекомендую повысить контраст между бекграундом сообщения собеседника и бекграундом чата

<img width="669" alt="изображение" src="https://github.com/user-attachments/assets/7d6ffcc3-059e-4fed-a664-ba7a61fcf7b6">

2024-11-25 04:27 UTC, sh4rkizz commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Хотелось бы увидеть доработанный api:
\- сохранение профиля
\- создание нового чата

2024-11-27 18:04 UTC, margo-yunanova commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
> Есть небольшая проблема с тем, что аватарка скукоживается, если последним сообщением является текст с переполнением [который транкируется элипсисом]
> 
> Стоит добавить либо фиксированную минимальную ширину для блока с аватаркой либо поиграться с значениями свойства `flex`
> 

@sh4rkizz , привет. Вроде починила, если ошибка ещё воспроизводится скажи в каком браузере ты смотришь?

2024-11-27 18:20 UTC, margo-yunanova commented on react-chat/src/pages/LoginPage/LoginPage.tsx
> +        </span>
Давай эти пункты я в 9-10 спринтах доделаю, чтобы побыстрее догнать дедлайны (на работе был завал и я отстала от графика по домашкам):

> По правильному - крестик должен появляться в той же области где рисовался бургер меню [он должен подменять его]

> Сейчас неясно как создать новый чат

> На странице реги присутствует ошибка фронта - где-то около парсинга токенов

> - создание нового чата [проверял на уже существующих в аккаунте чатах]

2024-11-27 20:27 UTC, margo-yunanova commented
@sh4rkizz , остальные замечания пофиксила, если нет возражений по переносу оставшихся доработок на другой спринт, то можно ревьювить.

2024-11-28 18:22 UTC, sh4rkizz requested changes

2024-11-28 18:22 UTC, sh4rkizz commented on react-chat/src/feature/Form/Form.tsx
> +              <input
Предлагаю помогать пользователю в выборе только корректного типа файла
https://stackoverflow.com/questions/4328947/limit-file-format-when-using-input-type-file

2024-11-28 18:22 UTC, sh4rkizz commented on react-chat/src/feature/Form/Form.tsx
> +              <input
![telegram-cloud-photo-size-2-5350547980094138264-y](https://github.com/user-attachments/assets/0d87abdd-71d1-4b73-8633-853270fac7fc)

Просьба в рамках 9 ДЗ обработать ошибки на клиенте [страница профиля]
Ошибка выводится под полем, при вводе в это поле - сбрасывается

Если есть общие ошибки - как например 429/500/502 и прочие, предлагаю использовать react-toastify
[или любую другую удобную алертницу, которой будет удобно пользоваться]

Так же в рамках 9 ДЗ ожидаю центрифугу, тем более что уже начала вкручивать и она работает на часть событий

2024-11-28 18:22 UTC, sh4rkizz commented on react-chat/src/feature/Form/Form.tsx
> +              <input
Здесь последнее сообщение - Фотография, при этом кажется будто чат совершенно пуст
Предлагаю об этом писать на странице чатов

Аналогично отсутствует инфа, если последнее сообщение - голосовое

"Фотография (<число приложенных файлов>)"
"Голосовое сообщение"

<img width="286" alt="изображение" src="https://github.com/user-attachments/assets/b3bd2ff6-37af-47e2-bbff-4c2b22d1f3d2">

2024-11-28 18:22 UTC, sh4rkizz commented on react-chat/src/feature/Form/Form.tsx
> +              <input
Сейчас на ПК неясно как взаимодействовать с ГС
Это модальное окно воспрепятствует моему взаимодействию с кнопкой

На телефоне, на удивление, работает корректно

<img width="333" alt="изображение" src="https://github.com/user-attachments/assets/22260c22-4f18-4202-aa42-fb2e946d332f">

2024-11-28 18:23 UTC, sh4rkizz commented on react-chat/src/feature/Form/Form.tsx
> +              <input
Крайний брейкпоинт адаптива - 320px
Давай поправим, вроде правка несложная

<img width="412" alt="изображение" src="https://github.com/user-attachments/assets/911cc17f-8061-41a6-90f2-dc7ccbcfba7f">

2024-11-28 18:29 UTC, sh4rkizz commented on react-chat/src/feature/Form/Form.tsx
> +              <input
Кажется что в приватной переписке [1 на 1] аватарки являются лишними
Можно отображать их по флагу чата is_private

Если оставлять - предлагаю уменьшить, поскольку занимают сейчас ощутимо большое пространство
А также переместить к нижнему краю сообщения, чтобы было не как на скрине

<img width="790" alt="изображение" src="https://github.com/user-attachments/assets/acd09a2c-73c4-413a-b013-7f3984c91d22">

2024-11-28 18:32 UTC, sh4rkizz commented on react-chat/src/feature/Form/Form.tsx
> +              <input
На странице списка чатов нет необходимости в запросе за каждым возможным чатом

Если на основе этого рисуется counter - то это ошибка
Его подсчет - ответственность бекенда [даже если он этого не делает]

<img width="555" alt="изображение" src="https://github.com/user-attachments/assets/a11071ab-2d98-4dfe-878e-9ae4a42da5dc">

2024-11-29 16:01 UTC, margo-yunanova commented on react-chat/src/feature/Form/Form.tsx
> +              <input
> На странице списка чатов нет необходимости в запросе за каждым возможным чатом
> 
> Если на основе этого рисуется counter - то это ошибка Его подсчет - ответственность бекенда [даже если он этого не делает]
> 
Т.к. бэкенд не присылает, я сама посчитала, хотела чтобы в был счетчик в реализации.

2024-11-30 13:51 UTC, sh4rkizz approved these changes
lgtm!

2024-11-30 13:51 UTC, sh4rkizz approved these changes
lgtm !!

2024-12-06 22:09 UTC, HaseProgram commented
Аппрув, 7!

2024-12-06 22:09 UTC, merged