Dz10
margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova pull request #16
Opened 2024-12-04 19:19 UTC by margo-yunanova

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @ проверить его.

Что было сделано:
Страница логина, интеграция с бэкендом, защищенные роуты были сделалы кажется в ДЗ 8. 
В этом ПР сделала логаут, и не возможность вернутся на форму логина.

По доработкам:
Сделала создание приватного чата, группового сделаю в 12 ДЗ
- [x] https://github.com/margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova/pull/12#discussion_r1855779045 - создание нового чата
- [x] https://github.com/margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova/pull/12#discussion_r1855763228 - кнопка создания нового чата

Эти исправления сделаю в 11 домашке, там как раз проанализировать сайт с помощью Lighthouse, он тоже возможно выдаст какие то замечания по accessibility:
- [ ] https://github.com/margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova/pull/14#discussion_r1868358379 - скругление аудио. В хроме он у меня скругленный, в сафари на телефоне тоже. В мозиле проверю на следующих домашках.
![image](https://github.com/user-attachments/assets/0caaaaa5-4706-4837-bf8a-0c7c9dbd8440)
- [ ] https://github.com/margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova/pull/14#discussion_r1868385350 - лоадер
- [ ] https://github.com/margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova/pull/14#discussion_r1868388037 - увеличить кнопки и интерактивные элементы
- [ ] https://github.com/margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova/pull/14#discussion_r1868394960 - увеличить шрифт
- [ ] https://github.com/margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova/pull/14#discussion_r1868396590 - контарст
- [ ] https://github.com/margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova/pull/14#discussion_r1868400805 - улучшить обработку ошибок при потыке зарегаться
- [ ] https://github.com/margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova/pull/14#discussion_r1868402244 - пофиксимть попытку обновления рефреш токена при регистрации

2024-12-06 14:11 UTC, sh4rkizz requested changes
Когда пользователь зарег [есть токены и они не протухшие]:
\- он не должен иметь возможность перейти на страницу `login/` или `register/`

2024-12-08 08:15 UTC, sh4rkizz submitted a review, later dismissed
lgtm!

2024-12-08 08:15 UTC, sh4rkizz approved these changes
lgtm v2

2024-12-09 11:06 UTC, merged

2024-12-09 11:07 UTC, martinkomitsky commented
7