Dz11
margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova pull request #18
Opened 2024-12-05 20:16 UTC by margo-yunanova

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
*
*
*

2024-12-06 14:23 UTC, sh4rkizz requested changes
когда заходишь на страницу чата lazy-loading ломает прокрутку чата
если есть возможность, поправь пожалуйста, чтобы при открытии чата окно было в нижней части списка сообщений, а не происходил скролл через 50 сообщений, среди которых могут быть картинки

2024-12-07 18:25 UTC, margo-yunanova commented
> когда заходишь на страницу чата lazy-loading ломает прокрутку чата если есть возможность, поправь пожалуйста, чтобы при открытии чата окно было в нижней части списка сообщений, а не происходил скролл через 50 сообщений, среди которых могут быть картинки

Привет, кроме как накостылить не вижу возможности сделать, было бы хорошо, если бы бэкенд присылал размеры картинок, тогда у скроллируемого контейнера был фиксированный размер, который не меняется по мере подгрузки картинок.
Максимум, что могу придумать, так это добавить перерасчёт высоты контейнера с сообщениями по мере загрузки картинок, тогда при последней высоте контейнера можно будет пролистать в конец.

https://stackoverflow.com/questions/7076970/problem-adjusting-scrollbar-after-images-have-been-loaded-on-page
https://www.reddit.com/r/webdev/comments/13kcpko/how_to_fix_jscss_scrolling_down_in_the_page_with/

2024-12-08 08:14 UTC, sh4rkizz approved these changes
lgtm

2024-12-08 08:16 UTC, sh4rkizz approved these changes
lgtm v2

2024-12-09 13:51 UTC, sh4rkizz approved these changes
lgtm v3 after stale !

2024-12-16 08:33 UTC, merged