Dz2
margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova pull request #2
Opened 2024-09-28 09:31 UTC by margo-yunanova

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:

![image](https://github.com/user-attachments/assets/4c68a27b-04c7-4888-90ab-e0029d4981b5)

2024-09-29 20:51 UTC, 1MarBur1 requested changes

2024-09-29 20:51 UTC, 1MarBur1 commented on simple-chat/main.js
> +  }
давай занесем второй и третьий инпут внутрь первого, вообще можем переписать на switch case, чтобы заложить на будущее другие статусы, типо "sending"

2024-09-29 20:51 UTC, 1MarBur1 commented on simple-chat/main.js
> +  input.style.height = '34.5px';
почему нам не сетать эти значения через css?

2024-09-29 20:51 UTC, 1MarBur1 commented on simple-chat/index.html
Длинное сообщение без пробелов ломает нашу верстку:

<img width="1440" alt="Снимок экрана 2024-09-29 в 23 46 36" src="https://github.com/user-attachments/assets/217d570a-e368-41c7-8016-a435f72f77a8">

Если вставлю длинное сообщение в инпут, он ведет себя не совсем ожидаемo:

<img width="1440" alt="Снимок экрана 2024-09-29 в 23 47 21" src="https://github.com/user-attachments/assets/fbcce6d8-4990-436b-818b-e2a1194be609">

2024-09-29 20:51 UTC, 1MarBur1 commented on simple-chat/index.html
кнопку для отправки сообщения тоже нужно добавить

2024-09-29 20:51 UTC, 1MarBur1 commented on simple-chat/index.html
ховер эффекты на иконки тоже можешь добавить)

2024-09-29 20:51 UTC, 1MarBur1 commented on simple-chat/index.html
В целом компонент сообщения ведет себя немного неожидаемо)

<img width="1088" alt="Снимок экрана 2024-09-29 в 23 50 41" src="https://github.com/user-attachments/assets/02397aad-a508-4637-83fd-e61bc0075e78">

2024-10-01 11:53 UTC, margo-yunanova commented on simple-chat/index.html
> +        </label>
done

2024-10-01 13:14 UTC, 1MarBur1 commented on simple-chat/index.html
сообщение выравнивается по левому краю, получается большой отступ справа

2024-10-01 13:40 UTC, margo-yunanova commented on simple-chat/main.js
> +  }
done

2024-10-01 13:51 UTC, margo-yunanova commented on simple-chat/main.js
> +  input.style.height = '34.5px';
Я задаю инлайновые стили, когда динамически изменяю высоту инпута в зависимости от содержимого. Стилями css без important, как я понимаю, это не перебить.

2024-10-01 17:12 UTC, margo-yunanova commented on simple-chat/index.html
Думаю, т.к. контент не помещается, ширина блока вычисляется по свойству max-width, оно у меня 75% ширины экрана. И поэтому контент уже распологается как может в этой ширине. Не думаю, что я на это могу повлиять.

В телеграмме точно также работает.  
![image](https://github.com/user-attachments/assets/987f9c2c-c255-4d7e-9075-0fd9f60e70f1)

2024-10-01 17:12 UTC, margo-yunanova commented on simple-chat/index.html
done

2024-10-02 11:13 UTC, 1MarBur1 approved these changes
@HaseProgram @martinkomitsky @kgrechin approved

2024-10-02 20:45 UTC, merged