Dz3
margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova pull request #3
Opened 2024-10-04 14:30 UTC by margo-yunanova

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:

![image](https://github.com/user-attachments/assets/717d178f-777a-44d1-820e-dbf3b833e495)

2024-10-13 09:21 UTC, 1MarBur1 requested changes
В рамках этого задания уже нужно реализовать создание чатов, открытие конкретного чата, а не моков и поиск

2024-10-13 09:21 UTC, 1MarBur1 commented on simple-chat/index.html
когда заходишь на страницу список сообщений прокручивается только до середины, а не до конца бокса

2024-10-13 09:45 UTC, margo-yunanova commented on simple-chat/index.html
Прокручивается не до середины, а до последнего прочитанного сообщения.

2024-10-13 09:51 UTC, margo-yunanova commented
> В рамках этого задания уже нужно реализовать создание чатов, открытие конкретного чата, а не моков и поиск

Это ДЗ-2 - такого в задании нет.
В задании написано:

Заверстать страницу, максимально разбив свой код компонентов (js/css) на разные файлы - **заверстала**
Предусмотреть переходы с экрана списка чатов на экран сообщений, который был реализован в предыдущем ДЗ - **здесь написано с экрана списка чатов во множественном числе на экран сообщений в единственном который был реализован в предыдущем ДЗ**. В предыдущем ДЗ мы верстали страницу чата, и у меня на неё переход.

Не понимаю про какой поиск идёт речь, я его не делала, и что значит реализовать создание чатов, где это написано. Нужно было сделать только **"Парящая" кнопка "создать чат"**.

2024-10-13 09:56 UTC, 1MarBur1 commented on simple-chat/index.html
Хм, если делать так - нужно скроллить до первого непрочитанного сообщения собеседника, как в телеге. Если наши сообщения последние в истории чата, но собеседник их еще не прочитал, то все равно скроллим до низу. Тк мы эти сообщения уже "прочитали".

2024-10-13 09:58 UTC, 1MarBur1 commented
В целом - можно реализовать и в след заданиях, но можешь и отличиться и сделать сейчас.

Если не будешь делать - тогда поправь скролл, выше описал и поставлю аппрув

2024-10-13 10:05 UTC, margo-yunanova commented
> В целом - можно реализовать и в след заданиях, но можешь и отличиться и сделать сейчас.
> 
> Если не будешь делать - тогда поправь скролл, выше описал и поставлю аппрув

Я уже сейчас на реакт переписываю, там сделаю тогда.

Можешь уточнить, что по скроллу? Я писала логику, что определяется первое непрочитанное сообщение и листается до него, как в телеграмме.
У меня в моках указано, что последние 3 сообщения не прочитаны, поэтому и листается не до конца блока. При скролле я не меняю статус моковым сообщениям.

2024-10-22 11:29 UTC, 1MarBur1 approved these changes
@martinkomitsky @HaseProgram @kgrechin approved

2024-10-23 16:51 UTC, merged

2024-10-23 16:51 UTC, martinkomitsky commented
12!