Dz4
margo-yunanova/2024-2-VK-EDU-Frontend-M-Yunanova pull request #4
Opened 2024-10-09 18:43 UTC by margo-yunanova

# Домашнее задание №4

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
1. Добавлен ripple эффект при клике на кнопки и на выбранный чат
2. Добавлено выделение при ховере чата
3. Кнопке создать новый чат добавлен пульсирующий эффект
4. Новое сообщение появлется с эффектом из центра

2024-10-23 17:00 UTC, martinkomitsky requested changes
Нужно исправить конфликт

2024-10-23 17:00 UTC, martinkomitsky commented
@1MarBur1 комменты будут?

2024-10-24 18:49 UTC, margo-yunanova commented
> Нужно исправить конфликт

@martinkomitsky , готово

2024-10-24 21:11 UTC, 1MarBur1 approved these changes
@martinkomitsky @HaseProgram @kgrechin approved

2024-11-05 09:24 UTC, martinkomitsky approved these changes

2024-11-05 09:24 UTC, merged

2024-11-05 09:25 UTC, martinkomitsky commented
12!